FROM golang:1.17

WORKDIR /app

COPY ./analytics/KLDDOS/kullbackleibler.go /app

RUN go mod init kullbackleibler

RUN go mod tidy

RUN go build kullbackleibler.go


ENTRYPOINT ["./kullbackleibler", "100000", "10000000", "5"]
